{% set name = 'pyside2qtads' if qt == '5' else 'pyside6qtads' %}
{% set version = "4.3.0.2" %}

{% set qt = '6' if qt == '' else qt %}

{% set version_list = version.split('.') %}
{% set version_list = version_list[:3] if version_list|length > 3 else version_list %}
{% set qtads_version = version_list|join('.') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mborgerson/pyside6_qtads/archive/v{{ version }}.tar.gz
  sha256: 210cc0a278a74e6b1ba9798086d1efa3760f494039d11daa14fffa6191d2f712
  patches:
    - 0001-CMakeLists.patch
    - 0002-generate_pyi_qt6.patch  # [qt==6]
    - 0002-generate_pyi_qt5.patch  # [qt==5] 
    - 0003-setup.patch
    - 0004-bindings.patch
    - 0005-init.patch

build:
  number: 0
  script: {{ PYTHON }} {{ RECIPE_DIR }}/replace_qt_version.py && {{ PYTHON }} -m pip install . -vv  # [qt==5]
  script: {{ PYTHON }} -m pip install . -vv  # [qt==6]
  # Shiboken2 is compatible with python up to 3.10
  skip: true  # [qt==5 and py>=311]
  # Pyside6>=6.7 is not built against python <3.9
  skip: true  # [qt==6 and py<39]
  ignore_run_exports_from:
    # Just used for shiboken/pyside not used for python module
    - clangdev  # [not osx]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - clangdev
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libglvnd-glx') }}      # [linux]
    - {{ cdt('libglvnd-egl') }}      # [linux]

  host:
    - python
    - cmake-build-extension
    - qt6-main                       # [qt==6]
    - qt6-advanced-docking-system =={{ qtads_version }}    # [qt==6]
    - pyside6                        # [qt==6]
    - qt-main                        # [qt==5]
    - qt5-advanced-docking-system =={{ qtads_version }}    # [qt==5]
    - pyside2                        # [qt==5]
    - pip
    - setuptools
    - xorg-libxfixes                 # [linux]
  run:
    - python
    - pyside6                        # [qt==6]
    - {{ pin_compatible('qt6-advanced-docking-system', max_pin='x.x.x') }}  # [qt==6]
    - pyside2                        # [qt==5]
    - {{ pin_compatible('qt5-advanced-docking-system', max_pin='x.x.x') }}  # [qt==5]

test:
  imports:
    - PySide6QtAds                   # [qt==6]
    - PySide2QtAds                   # [qt==5]

about:
  home: https://github.com/mborgerson/pyside6_qtads
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: PySide6 bindings for Qt-Advanced-Docking-System  # [qt==6]
  summary: PySide2 bindings for Qt-Advanced-Docking-System  # [qt==5]

extra:
  recipe-maintainers:
    - n-elie
